/*
 * Decompiled with CFR 0.149.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
package net.minecraft.structure;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;
import net.minecraft.class_5468;
import net.minecraft.class_5469;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElement;
import net.minecraft.util.Identifier;

public class BastionTreasureData {
    public static void init() {
    }

    static {
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/bases"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/bases/lava_basin", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/stairs"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/stairs/lower_stairs", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/bases/centers"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/bases/centers/center_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/bases/centers/center_1", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/bases/centers/center_2", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/bases/centers/center_3", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/brains"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/brains/center_brain", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/walls"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/lava_wall", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/entrance_wall", class_5469.HIGH_WALL), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/walls/outer"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/outer/top_corner", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/outer/mid_corner", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/outer/bottom_corner", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/outer/outer_wall", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/outer/medium_outer_wall", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/outer/tall_outer_wall", class_5469.HIGH_WALL), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/walls/bottom"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/bottom/wall_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/bottom/wall_1", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/bottom/wall_2", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/bottom/wall_3", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/walls/mid"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/mid/wall_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/mid/wall_1", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/mid/wall_2", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/walls/top"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/top/main_entrance", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/top/wall_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/walls/top/wall_1", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/connectors"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/connectors/center_to_wall_middle", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/connectors/center_to_wall_top", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/connectors/center_to_wall_top_entrance", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/entrances"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/entrances/entrance_0", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/ramparts"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/ramparts/mid_wall_main", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/ramparts/mid_wall_side", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/ramparts/bottom_wall_0", class_5469.BOTTOM_RAMPART), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/ramparts/top_wall", class_5469.HIGH_RAMPART), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/ramparts/lava_basin_side", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/ramparts/lava_basin_main", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/corners/bottom"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/bottom/corner_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/bottom/corner_1", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/corners/edges"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/edges/bottom", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/edges/middle", class_5469.HIGH_WALL), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/edges/top", class_5469.HIGH_WALL), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/corners/middle"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/middle/corner_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/middle/corner_1", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/corners/top"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/top/corner_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/corners/top/corner_1", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/extensions/large_pool"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/empty", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/empty", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/fire_room", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/large_bridge_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/large_bridge_1", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/large_bridge_2", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/large_bridge_3", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/roofed_bridge", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/empty", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/extensions/small_pool"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/empty", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/fire_room", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/empty", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/small_bridge_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/small_bridge_1", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/small_bridge_2", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/small_bridge_3", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/extensions/houses"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/house_0", class_5469.TREASURE_ROOMS), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/extensions/house_1", class_5469.TREASURE_ROOMS), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/treasure/roofs"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/roofs/wall_roof", class_5469.ROOF), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/roofs/corner_roof", class_5469.ROOF), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/treasure/roofs/center_roof", class_5469.ROOF), (Object)1)), StructurePool.Projection.RIGID));
    }
}

