/*
 * Decompiled with CFR 0.149.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
package net.minecraft.structure;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;
import net.minecraft.class_5468;
import net.minecraft.class_5469;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElement;
import net.minecraft.util.Identifier;

public class HoglinStableData {
    public static void init() {
    }

    static {
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/starting_pieces"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/starting_stairs_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/starting_stairs_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/starting_stairs_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/starting_stairs_3", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/starting_stairs_4", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/mirrored_starting_pieces"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/stairs_0_mirrored", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/stairs_1_mirrored", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/stairs_2_mirrored", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/stairs_3_mirrored", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/starting_pieces/stairs_4_mirrored", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/wall_bases"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/walls/wall_base", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/walls"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/walls/side_wall_0", class_5469.SIDE_WALL_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/walls/side_wall_1", class_5469.SIDE_WALL_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/stairs"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_1_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_1_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_1_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_1_3", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_1_4", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_2_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_2_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_2_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_2_3", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_2_4", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_3_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_3_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object[])new Pair[]{Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_3_2", class_5469.STABLE_DEGRADATION), (Object)1), Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_3_3", class_5469.STABLE_DEGRADATION), (Object)1), Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/stairs/stairs_3_4", class_5469.STABLE_DEGRADATION), (Object)1)}), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/small_stables/inner"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/inner_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/inner_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/inner_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/inner_3", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/small_stables/outer"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/outer_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/outer_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/outer_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/small_stables/outer_3", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/large_stables/inner"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/inner_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/inner_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/inner_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/inner_3", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/inner_4", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/large_stables/outer"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/outer_0", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/outer_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/outer_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/outer_3", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/large_stables/outer_4", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/posts"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/posts/stair_post", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/posts/end_post", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/ramparts"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/ramparts/ramparts_1", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/ramparts/ramparts_2", class_5469.STABLE_DEGRADATION), (Object)1), (Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/ramparts/ramparts_3", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/rampart_plates"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/rampart_plates/rampart_plate_1", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
        class_5468.method_30600(new StructurePool(new Identifier("bastion/hoglin_stable/connectors"), new Identifier("empty"), (List<Pair<Function<StructurePool.Projection, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.method_30435("bastion/hoglin_stable/connectors/end_post_connector", class_5469.STABLE_DEGRADATION), (Object)1)), StructurePool.Projection.RIGID));
    }
}

